"""num5

Revision ID: 13d198fee64b
Revises: 99c5a2d40a11
Create Date: 2023-05-17 11:07:00.079459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d198fee64b'
down_revision = '99c5a2d40a11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
