"""num5

Revision ID: 357ac2e53abe
Revises: d7db28a984ee
Create Date: 2023-05-18 23:20:56.562597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357ac2e53abe'
down_revision = 'd7db28a984ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
