"""num5

Revision ID: 367964791313
Revises: 588a7d84fd80
Create Date: 2023-05-12 13:15:19.149466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367964791313'
down_revision = '588a7d84fd80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
